### ISSUE TITLE
deduplication: symlinks/hardlinks instead of others.txt

### ISSUE THREAD

**Issue by saladpanda** [mholt/photobak#1]
It would be great if you could create symlinks or hardlinks for deduplication instead of creating an `others.txt` file with paths to photos.

**Comment by mholt** [comment]
I thought about that, and there are both advantages and disadvantages to either. I simply chose to go with the text file. They're perfectly cross-platform compatible, save on inodes, and are human readable as well as computer-parsable. Thanks for your suggestion!

**Comment by n03l** [comment]
I think the advantage of having links is that you can view albums with any software (as regular folders full of pictures). 

Would it be possible to have this behavior depending on a flag?
