### ISSUE TITLE
Photo captions

### ISSUE THREAD

**Issue by drastus** [mholt/photobak#11]
I know that photo captions (descriptions) from Google Photos are stored in photobak.db, but how can I extract them into usable form? Maybe there should be an option to save Google Photos captions as Exif 'Title' metadata in downloaded photos?

**Comment by mholt** [comment]
That's possible, but rather than mess with the photo's metadata, I'd rather make an interface for extracting the information in the database. Hasn't really been a need for me (yet--hopefully never!) but it's definitely a long-term TODO.

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
