### ISSUE TITLE
Handling duplicated file names

### ISSUE THREAD

**Issue by jkl1337** [mholt/photobak#12]
It looks like this is not dealing too well with photos with the same name. Hangouts apparently saved images from the same day with the same name (just the date) and the tool doesn't rename these duplicates. Every time the command is rerun of course it detects it as a checksum error and redownloads.

**Comment by mholt** [comment]
Hmm, that doesn't sound right; we use the item's ID, not its filename, to distinguish duplicates: https://github.com/mholt/photobak/blob/84180cea804f357c6bb007fa9602f83ca209cafb/googlephotos/xmlstruct.go#L110

Maybe the file is not downloading correctly instead?

**Comment by jkl1337** [comment]
Ah fair enough. I didn't actually debug the problem (due to lack of time right now). The images were all from hangouts a few years ago, and demonstrate the repeating name pattern (and there is ultimately only one file left in the directory). I'll see if I can look into it more later.

**Comment by mholt** [comment]
I've experienced something similar on a few of my photos (not Hangouts ones, although I have several of those) and am not sure if a recent PR may have fixed it. Haven't looked into it too much recently.

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
