### ISSUE TITLE
Error after a day of use

### ISSUE THREAD

**Issue by luc-lynx** [mholt/photobak#14]
After using the app for a day I'm getting the following error:

```
2017/10/22 15:57:19 Get https://picasaweb.google.com/data/feed/api/user/default: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_request",
  "error_description" : "Could not determine client ID from request."
}
```

I'm using the app in a headless mode, so I ran authonly and copied the database to my NAS. Then I made a backup and the next day I'm getting the error above. How can I recover? Did anyone come across the same issue?

**Comment by luc-lynx** [comment]
The problem disappears if I do 

```
$ export GOOGLEPHOTOS_CLIENT_ID=...
$ export GOOGLEPHOTOS_CLIENT_SECRET=...
```

So it would be great to put the values to the account database

**Comment by mholt** [comment]
Oh, right; the client ID and secret still have to be given, I guess that's not clear from the readme. Sorry. I guess we could store them in the DB too, with the option for env variables to override the stored values, for cases like this.

**Comment by luc-lynx** [comment]
Thanks for the quick response. btw I can fix it myself and send you a PR, if you haven't started to implement it

**Comment by mholt** [comment]
I haven't -- go for it!

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
