### ISSUE TITLE
Photo metadata is changed in download

### ISSUE THREAD

**Issue by gosanke** [mholt/photobak#15]
I might miss something but when downloading the photos and checking 'create' and 'modified' dates - they are all from today and time downloaded.
See attached screenshots from picture in Google Photos and from downloaded photo locally.
Am I missing something or doing something wrong?
![screenshot 2017-11-01 22 27 27](https://user-images.githubusercontent.com/939351/32299002-46d069e6-bf54-11e7-8c89-e60d4dab5c40.png)
![screenshot 2017-11-01 22 27 42](https://user-images.githubusercontent.com/939351/32299003-47199e90-bf54-11e7-9b80-ad3557a38532.png)

![screenshot 2017-11-01 23 04 20](https://user-images.githubusercontent.com/939351/32300281-1ad41b6c-bf59-11e7-8fcd-9102fa451242.png)

**Comment by mholt** [comment]
In Google Photos, you're looking at the _photo_ metadata (embedded EXIF data) but in Finder you're viewing the _file_ metadata (created by the file system). Open Preview, then Show Inspector and you will see the photo's original Date Time there. :)
