### ISSUE TITLE
Download breaks - a fraction of photos downloaded

### ISSUE THREAD

**Issue by gosanke** [mholt/photobak#16]
The process seems to be running fine but on 2 seperate accounts similar errors start showing up and after a while the program breaks and exits.
I've tried a couple of times to re-start the process without luck - do you have any suggestions?
Thanks on beforehand :) 
![screenshot 2017-11-02 00 59 23](https://user-images.githubusercontent.com/939351/32303562-9cdff0e4-bf69-11e7-9231-e8b2751e33a9.png)
![screenshot 2017-11-02 00 59 50](https://user-images.githubusercontent.com/939351/32303563-9cfebe02-bf69-11e7-8cb1-3d8c53831d7c.png)
![screenshot 2017-11-02 01 04 29](https://user-images.githubusercontent.com/939351/32303605-da34c71c-bf69-11e7-98fe-0bfda4f12469.png)

![screenshot 2017-11-02 01 06 04](https://user-images.githubusercontent.com/939351/32303643-106ce508-bf6a-11e7-8fe6-435ef8f7be78.png)

**Comment by mholt** [comment]
Uhhh wow that's a lot of errors. How long ago were those videos uploaded? I'm not sure there's much you can do in this case. Sorry...

**Comment by sundarv85** [comment]
@mholt How long can we go back? ie. does it matter when the videos are uploaded. If so, do you have a time from which we can start the backup instead of backing up everything in Google Photos.

**Comment by mholt** [comment]
I think the very undocumented and highly arbitrary limit in the "Picasa Web Albums API" is like 10k photos per album. Unfortunately.

The solution to this *might* be to put old photos in albums with a max of 10K per album. Or 1k, just to be safe and keep things manageable.

You could also use the Google Takeout service to do a one-time download of all your photos and videos, and let photobak just nab the newest ones.
