### ISSUE TITLE
OAuth2 hanging at "Waiting for localhost..."

### ISSUE THREAD

**Issue by davidradkowski** [mholt/photobak#17]
I've just tried to start and authenticate the app, however, I got stuck at the OAuth2 authentication step. The app opens a web browser (checked with both chromium and Firefox) in which I successfully log into my account but subsequently the webpage starts to wait with "Waiting for localhost" status bar message. The app is waiting for something as well with a message about obtaining tokens. 
Have I missed anything? What are the web browser and the app waiting for??  (I have client's ID and secret exported)

Cheers

**Comment by mholt** [comment]
After OAuth2 is authorized by you, the web page should connect to a localhost server on port 5013 to relay the token. Apparently it's not making that connection. Do you have a firewall? If so, disable it or allow inbound connections on port 5013.

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
