### ISSUE TITLE
oauth2: token expired and refresh token is not set

### ISSUE THREAD

**Issue by viperx77** [mholt/photobak#18]
After some period of time (I think one hour) I get this error and sync will no longer work.

**Comment by mholt** [comment]
Interesting -- did you go through the authentication process at first to set it up, and has it been working okay since then? Meaning, it just stops after 1 hour after setting it up?

Or by "sync" do you mean the process of downloading the photos is happening continuously for an hour, and then it breaks? If you could be more specific about what you're doing, that will help.

**Comment by viperx77** [comment]
So I deleted my local content and started over.  Here's the command:

```
photobak -googlephotos [redacted]@gmail.com
```

And here's the output:

```
2018/01/07 14:26:08 Getting new OAuth2 token
2018/01/07 15:31:03 listing collection items (attempt 1): Get https://picasaweb.google.com/data/feed/api/user/default/albumid/1000000486896946?imgmax=d&start-index=3001: oauth2: token expired and refresh token is not set
2018/01/07 15:31:03 listing collection items (attempt 2): Get https://picasaweb.google.com/data/feed/api/user/default/albumid/1000000486896946?imgmax=d&start-index=1: oauth2: token expired and refresh token is not set
2018/01/07 15:31:03 listing collection items (attempt 3): Get https://picasaweb.google.com/data/feed/api/user/default/albumid/1000000486896946?imgmax=d&start-index=1: oauth2: token expired and refresh token is not set
2018/01/07 15:31:03 [ERROR] processing Auto Backup: client error listing collection items, giving up: Get https://picasaweb.google.com/data/feed/api/user/default/albumid/1000000486896946?imgmax=d&start-index=1: oauth2: token expired and refresh token is not set
```

It downloaded 28gb before it crapped out after a little over an hour.  When I start it again with the command:

```
photobak -googlephotos [redacted]@gmail.com
```

It immediately responds with:

`2018/01/07 18:37:24 Get https://picasaweb.google.com/data/feed/api/user/default: oauth2: token expired and refresh token is not set
`

I hope that's clear.  Am I doing something wrong?

**Comment by ameesme** [comment]
A temporary workaround is to create new credentials using a different installation of `photobak`, and then manually modifying `photobak.db` (which is a BoltDB) using a utility like [boltbrowser](https://github.com/br0xen/boltbrowser).

**Comment by mholt** [comment]
I think I've seen this happen when re-authenticating after your application was already authorized by Google; I've been able to fix it by removing the app's access: https://myaccount.google.com/permissions - and then re-authenticating from scratch (doesn't require deleting all the data).

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
