### ISSUE TITLE
Getting an `invalid_client` error when setting it up

### ISSUE THREAD

**Issue by ondrejsevcik** [mholt/photobak#21]
Hi, I was trying to use this tool for the first time, but I'm getting an `invalid_client` error. 

I've put my OAuth2 info but it seems it doesn't like that. I'm probably doing something wrong in google console. Can you help me navigate where should I create correct OAuth2 credentials? 

Thank you 🙏🏽

![image](https://user-images.githubusercontent.com/4136929/40808019-2d557c9a-6526-11e8-9df1-4286ce9ad177.png)

**Comment by mholt** [comment]
This project has been deprecated in favor of [Timeliner](https://github.com/mholt/timeliner). Thank you!
