### ISSUE TITLE
Anyway to see current status

### ISSUE THREAD

**Issue by m-rufflesmcghie** [mholt/photobak#23]
Hi, love the program hoping to contribute more once setup properly...one question...is their any way of seeing current status of download. Have just set up Google to sync for first time photos are appearing and it's still running in terminal just no status...

**Comment by mholt** [comment]
Have you tried using the `-log` and `-v` flags?

**Comment by m-rufflesmcghie** [comment]
Just got up left it running all night, had few errors with some MP4 files, also 
"client error listing collection items, giving up:EOF"
Just re-run with the flags above will keep you updated.
Thanks for your quick reply :-)
