### ISSUE TITLE
How do I execute this on Mac?

### ISSUE THREAD

**Issue by nchaurdia** [mholt/photobak#7]
$ export GOOGLEPHOTOS_CLIENT_ID=...
$ export GOOGLEPHOTOS_CLIENT_SECRET=...
$ photobak -googlephotos you@yours.com

I got my IDs but not sure how to run it.

**Comment by mholt** [comment]
The first time you run it, you'll be redirected to a browser page to authorize your program. Did you do that? After that happens, photobak will begin your backup. You can stop and restart it any time if you need to.

**Comment by nchaurdia** [comment]
How do I run it though?

**Comment by mholt** [comment]
Just like you did above: `photobak -googlephotos you@yours.com`

**Comment by nchaurdia** [comment]
THanks!
